WebApplication1/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Name { get; set; }
        public DateTime CreationDate { get; set; }
        public int? BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}

WebApplication1/Controllers/APISearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using WebApplication1.ViewModels;
using System.Security.Claims;
using BlogHost.BLL.Interfaces;
using BlogHost.BLL.DTO;
using AutoMapper;
//using System.Web.UI;
//using System.Web.Script.Serialization;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication1.Controllers
{
    //[Route("api/[controller]")]
    [Produces("application/json")]
    public class APISearchController : Controller
    {
        IUnit db { get; set; }

        public APISearchController(IUnit uow)
        {
            db = uow;
        }


        [HttpGet("/api/search")]
        public IActionResult Get(string searchstring)
        {

            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<BlogDTO, ViewBlogsModel>().ForMember("Author", opt => opt.MapFrom(c => db.Users.GetUserById((int)c.UserId).Login))).CreateMapper();
            List<ViewBlogsModel> blogs = mapper.Map<IEnumerable<BlogDTO>, List<ViewBlogsModel>>(db.Blogs.GetAllBlogs());

            if (!String.IsNullOrEmpty((string)searchstring))
            {
                blogs = mapper.Map<IEnumerable<BlogDTO>, List<ViewBlogsModel>>(db.Blogs.GetBlogsBySearchRequest((string)searchstring));
            }
           
            List<object> blogs2 = new List<object>();
            foreach (var t in blogs)
            {
                blogs2.Add(fun(t));
            }
    
            return Ok(blogs2);
        }


        [HttpGet("/api/searchposts")]
        public IActionResult SearchPosts(string searchstring, int? blogid)
        {

            List<PostDTO> posts = db.Posts.GetPostsAll();
            
            if (!String.IsNullOrEmpty(searchstring))
            {
                posts =db.Posts.GetPostsBySearchRequest(searchstring);
            }
            if (blogid != -1)
            {
                posts = posts.Where(u => u.BlogId == blogid).ToList();
            }

            List<object> posts2 = new List<object>();
            foreach (var t in posts)
            {
                posts2.Add(PostToObj(t));
            }


            return Ok(posts2);

        }

        public IActionResult SearchPosts(string searchstring)
        {

            List<PostDTO> posts = db.Posts.GetPostsAll();

            if (!String.IsNullOrEmpty(searchstring))
            {
                posts = db.Posts.GetPostsBySearchRequest(searchstring);
            }

            List<object> posts2 = new List<object>();
            foreach (var t in posts)
            {
                posts2.Add(PostToObj(t));
            }


            return Ok(posts2);

        }

        private object PostToObj(PostDTO post)
        {
            object obj = new { id = post.Id, author = db.Users.GetUserById((int)post.UserId).Login, name = post.Name, creationdate = post.CreationDate.ToString("F") };
            return obj;
        }


        private object fun(ViewBlogsModel par)
        {
            object res = new { id = par.Id, author = par.Author, name = par.Name, creationdate = par.CreationDate.ToString("F") };
            return res;
        }

        // GET api/<controller>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

WebApplication1/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Models;
using WebApplication1.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using BlogHost.BLL.Interfaces;
using BlogHost.BLL.DTO;

namespace WebApplication1.Controllers
{ 

    public class PostsController : Controller
    {
        IUnit db { get; set; }

        public PostsController(IUnit uow)
        {
            db = uow;
        }

        [HttpGet("/Posts/{id:int?}", Name = "Posts")]
        public IActionResult Index(int? id)
        {
            ViewData["BlogId"] = id;
            /*if (id == null)
            {
                var posts = db.Posts.GetPostsAll();
                return View(posts);
            }
            var post = db.Posts.GetPostsByBlog((int)id);*/
            return View();//post);
        }


        [Authorize(Roles = "1, 2")]
        [HttpGet("/Posts/create/{id:int?}", Name = "createpost")]
        public IActionResult Create()
        {    
            return View();
        }

        [HttpPost("/Posts/create/{id:int?}", Name = "createpost")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "1, 2")]
        public IActionResult Create(int? id, CreatePostModel model)
        {
            if (db.Users.GetUserById((int)db.Blogs.GetBlogByID((int)id).UserId).Email == User.Identity.Name)
            { 
                if (ModelState.IsValid)
                {                   
                    var post = new PostDTO { Name = model.Name, CreationDate = DateTime.Now, BlogId = (int)id, Text = model.Text, UserId = db.Users.GetIdByEmail(User.Identity.Name),  };
                    db.Posts.SavePost(post);
                    return RedirectToAction("Index", "Blog");
                }
                return View(model);
            }   
            return RedirectToAction("Index", "Blog");
        }

        [HttpGet("/Posts/info/{id:int}", Name = "AboutPost")]
        public IActionResult Info(int id)
        {
            var post = db.Posts.GetPostById(id);
            ViewData["PostsName"] = post.Name;
            ViewData["PostsText"] = post.Text;
            ViewData["PostsId"] = id;
            return View();
        }

        [HttpPost("/Posts/info/{id:int}", Name = "AboutPost")]
        [ValidateAntiForgeryToken]
        public IActionResult Info(int id, CreateCommentsModel model)
        {
            var post = db.Posts.GetPostById(id);
            ViewData["PostsName"] = post.Name;
            ViewData["PostsText"] = post.Text;
            ViewData["PostsId"] = id;
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                CommentDTO com = new CommentDTO { Text = model.Text, CreationDate = DateTime.Now, PostId = id, UserId = db.Users.GetIdByEmail(User.Identity.Name) };
                db.Comments.SaveComment(com);
            }
            return View(model);
        }


        [HttpGet("/Posts/delete/{id:int}", Name = "deletePost")]
        [Authorize(Roles = "1, 2")]
        public IActionResult Delete(int id)
        {
            //////// чекнуть какой ид передается эт может быть ид блога///всё норм) 
            if (db.Users.GetUserById((int)db.Posts.GetPostById(id).UserId).Email == User.Identity.Name)
            {
                db.Posts.DeletePost(id);
            }
            return RedirectToAction(nameof(Index));
        }

        /*public async Task<IActionResult> Index(int id)
        {
            return View();
        }*/

        // GET: Blogs/Edit/5
        [HttpGet("/Posts/edit/{id:int?}", Name = "editPost")]
        public IActionResult Edit(int? id, CreatePostModel model)
        {
            PostDTO post = db.Posts.GetPostById((int)id);
            model.Name = post.Name;
            model.Text = post.Text;
            return View(model);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/Posts/edit/{id:int?}", Name = "editPost")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CreatePostModel model)
        {
            if (ModelState.IsValid)
            {
                PostDTO post = db.Posts.GetPostById(id);
                post.Name = model.Name;
                post.Text = model.Text;
                db.Posts.UpdatePost(post);
            }
            return View(model);
        }
    }
}

WebApplication1/Views/Posts/Create.cshtml
@model WebApplication1.ViewModels.CreatePostModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


<h2>@Localizer["Header"]</h2>

<form asp-action="Create" asp-controller="Posts" asp-anti-forgery="true">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div>
            <label asp-for="Name">@Localizer["InName"]</label><br />
            <input type="text" asp-for="Name" />
            <span asp-validation-for="Name" />
        </div>
        <div>
            <label asp-for="Text">@Localizer["InTxt"]</label><br />
            <textarea type="text" asp-for="Text">Text</textarea>
            <span asp-validation-for="Text" />
        </div>
        <div>
            <input type="submit" value="@Localizer["BtnCreate"]" />
        </div>
    </div>
</form>

WebApplication1/Views/Posts/Edit.cshtml
@model WebApplication1.ViewModels.CreatePostModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<h2>@Localizer["Header"]</h2>

<form asp-action="Edit" asp-controller="Posts" asp-anti-forgery="true">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div>
            <label asp-for="Name">@Localizer["InName"]</label><br />
            <input type="text" asp-for="Name" />
            <span asp-validation-for="Name" />
        </div>
        <div>
            <label asp-for="Text">@Localizer["InText"]</label><br />
            <textarea type="text" asp-for="Text">Text</textarea>
            <span asp-validation-for="Text" />
        </div>
        <div>
            <input type="submit" value="@Localizer["Save"]" />
        </div>
    </div>
</form>

WebApplication1/Views/Posts/Index.cshtml
@model IEnumerable<BlogHost.BLL.DTO.PostDTO>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Index";
}

<h2>@Localizer["Header"]</h2>
@if (ViewBag.BlogId != null)
{
    <p>
        <a asp-action="Create" asp-route-id="@ViewBag.BlogId">@Localizer["CrPost"]</a>
    </p>
}
else
{
    ViewBag.BlogId = -1;
}
<form id="SearchForm" asp-action="SearchPosts" asp-controller="APISearch" method="get" name="form" onsubmit="return false;">
    <p>
        @Localizer["Search"]<br>
        <input name="search" type="text" id="search">
        <small></small>
    </p>
</form>

<div id="resSearch"></div>




<script type="text/javascript">
    $(document).ready(function () {
        go();//initiating the function for the 1st time.
    });

    $(function () {

        $("#search").keyup(function () {
            go();
        });
        return false;
    });

    function go() {
        var search = $("#search").val();
        var jsonText = JSON.stringify({ searchstring: search });
        $.ajax({
            type: "GET",
            url: "/api/searchposts/",
            contentType: "application/json; charset=utf-8",
            data: "searchstring=" + search + "&blogid=" + @ViewBag.BlogId,
            success: function (response) {
                    var fullstring = '<table class="table"><tbody>';
                for (var item in response) {
                        var htmlforview = "<tr><td><a href='/Posts/info/" + response[item].id + "/'>" + response[item].name + "</a></td><td>" + response[item].creationdate + "</td><td>" + response[item].author + "</td><td><a href='/Posts/delete/" + response[item].id + "/'>@Localizer["Delete"]</a></td><td><a href='/Posts/edit/" + response[item].id + "/'>@Localizer["Edit"]</a></td></tr>"
                    fullstring += htmlforview;
                    };
                    fullstring += "</tbody></table >";
                $("#resSearch").html(fullstring);
                }
            })
    };
</script>

WebApplication1/Views/Posts/Info.cshtml
@model WebApplication1.ViewModels.CreateCommentsModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Info";
}

<h2>@ViewData["PostsName"]</h2>

<p>
    @ViewData["PostsText"]
</p>

<form asp-action="Info" asp-controller="Posts" asp-anti-forgery="true">
    <div class="validation" asp-validation-summary="ModelOnly" />
    <div>
        <div class="form-group">
            <label asp-for="Text">@Localizer["CommText"]</label>
            <textarea type="text" asp-for="Text"> </textarea>
            <span asp-validation-for="Text" />
        </div>
        <div class="form-group">
            <input type="submit" value="@Localizer["BtnComm"]" class="btn" />
        </div>
    </div>
</form>

@await Component.InvokeAsync("CommentsComponents", new { id = @ViewData["PostsId"] })